services:
  - type: web
    name: one-raices-link-in-bio
    runtime: static
    staticPublishPath: ./
    buildCommand: ""
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
